config/routes.rb
Rails.application.routes.draw do
  # ユーザー側
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  
  root to: "homes#top"
  get '/about' => 'homes#about'
  get "/search", to: "searches#search"
  
  scope module: :public do
    get 'users/mypage' => 'users#mypage', as:'mypage'
    get 'users/information/edit' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update', as: 'update_information'
    get 'users/unsubscribe' => 'users#unsubscribe'
    put 'users/information' => 'users#update'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
    get 'users/:id', to: 'users#show', as: 'user'
    
    resources :users do
      resource :relationships, only: [:create, :destroy], path: 'user_relationships'
        get 'followings', to: 'relationships#followings', as: 'followings'
        get 'followers', to: 'relationships#followers', as: 'followers'
    end  
      
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :favorites, only: [:index]
    
    resources :notifications, only: [:index] do
      member do
        patch :mark_as_read
      end
    end
  end
  
  # 管理者側
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    get '/' => 'homes#top'
    get "/search", to: "searches#search"
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:show, :edit, :update]
    resources :comments, only: [:index,:show, :destroy]
    resources :posts, only: [:show, :index, :destroy]
  end
    devise_scope :admin do
    get '/admin/sign_out', to: 'admin/sessions#destroy'
  end
  
end

app/controllers/admin/searches_controller.rb
class Admin::SearchesController < ApplicationController
  before_action :authenticate_admin!
  
  def search
    if params[:search_target] == 'ユーザー'
      @results = User.search_for(params[:keyword], params[:method])
    elsif params[:search_target] == '投稿'
      @results = Post.search_for(params[:keyword], params[:method])
    elsif params[:search_target] == 'コメント'
      @results = Comment.search_for(params[:keyword], params[:method])  
    end

    if params[:method] == '部分一致'
      @results = @results.where('name LIKE ?', '%' + params[:keyword] + '%')
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user_or_admin!
  

  def search
    if params[:search_target] == 'ユーザー'
      @results = User.search_for(params[:keyword], params[:method])
    elsif params[:search_target] == '投稿'
      @results = Post.search_for(params[:keyword], params[:method])
    end

    if params[:method] == '部分一致'
      @results = @results.where('name LIKE ?', '%' + params[:keyword] + '%')
    end
  end
  
  private
  
  def authenticate_user_or_admin!
    unless user_signed_in? || admin_signed_in?
      redirect_to new_user_session_path, alert: "アクセスするにはログインが必要です。"
    end
  end
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/searches/_form.html.erb
<% if admin_signed_in? %>
  <%= form_with(url: admin_search_path, method: :get, class: "form-inline d-flex") do |form| %>
    <div class="form-group mr-2">
      <%= form.select(:search_target, @search_options.concat([['コメント', 'コメント']]), { include_blank: false }, class: "form-control") %>
    </div>
    <div class="input-group mr-2">
      <%= form.text_field :keyword, placeholder: "キーワードを入力", value: params[:keyword], class: "form-control" %>
      <div class="input-group-append">
        <%= form.button type: :submit, class: "btn btn-primary", id: "button-addon2" do %>
          <i class="fa-solid fa-magnifying-glass"></i>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/searches/search.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col'>
      <h4 class="underline mt-2">検索結果</h4>

      <div class="mt-2">
        <% if @results.present? %>
          <table class='table'>
            <% @results.each do |result| %>
              <% if result.is_a?(User) %>
                <tr>
                  <th>ユーザー名</th>
                  <td><%= result.nickname %></td>
                  <td><%= link_to '詳細', admin_user_path(result), class:"btn btn-success" %></td>
                </tr>
              <% elsif result.is_a?(Post) %>
                <tr>
                  <th>投稿名</th>
                  <td><%= result.name %></td>
                  <td><%= link_to '詳細', admin_post_path(result), class:"btn btn-success" %></td>
                </tr>
              <% elsif result.is_a?(Comment) %>
                <tr>
                  <th>コメント</th>
                  <td><%= result.comment %></td>
                  <td><%= link_to '詳細', admin_comment_path(result), class:"btn btn-success" %></td>
                </tr>
              <% end %>
            <% end %>
          </table>
        <% else %>
          <p>検索結果はありません。</p>
        <% end %>
      </div>

    </div>
  </div>
</div>