config/routes.rb
Rails.application.routes.draw do
  # ユーザー側
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  
  root to: "homes#top"
  get '/about' => 'homes#about'
  get "/search", to: "searches#search"
  
  scope module: :public do
    get 'users/mypage' => 'users#mypage', as:'mypage'
    get 'users/information/edit' => 'users#edit', as: 'edit_information'
    patch 'users/information' => 'users#update', as: 'update_information'
    get 'users/unsubscribe' => 'users#unsubscribe'
    put 'users/information' => 'users#update'
    patch 'users/withdraw' => 'users#withdraw', as: 'withdraw_user'
    get 'users/:id', to: 'users#show', as: 'user'
    
    resources :users do
      resource :relationships, only: [:create, :destroy], path: 'user_relationships'
        get 'followings', to: 'relationships#followings', as: 'followings'
        get 'followers', to: 'relationships#followers', as: 'followers'
    end  
      
    resources :posts do
      resource :favorite, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    resources :favorites, only: [:index]
    
    resources :notifications, only: [:index] do
      member do
        patch :mark_as_read
      end
    end
  end
  
  # 管理者側
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  namespace :admin do
    get '/' => 'homes#top'
    get "/search", to: "searches#search"
    resources :genres, only: [:index, :create, :edit, :update, :destroy]
    resources :users, only: [:show, :edit, :update]
    resources :comments, only: [:index,:show, :destroy]
    resources :posts, only: [:show, :index, :destroy]
  end
    devise_scope :admin do
    get '/admin/sign_out', to: 'admin/sessions#destroy'
  end
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  has_many :notifications, as: :notifiable, dependent: :destroy
  
  validates :comment, presence: true, length: {maximum: 200 }
  
  def self.search_for(content, method)
    if method == 'perfect'
      Comment.where(comment: content)
    elsif method == 'forward'
      Comment.where('comment LIKE ?', content + '%')
    elsif method == 'backward'
      Comment.where('comment LIKE ?', '%' + content)
    else
      Comment.where('comment LIKE ?', '%' + content + '%')
    end
  end
  
  private
  def create_notification
    Notification.create(
      user: self.post.user,
      notifiable: self
      )
  end    
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  after_create :create_notification
  
  belongs_to :user
  belongs_to :post
  has_many :notifications, as: :notifiable, dependent: :destroy
  
  validates :user_id, uniqueness: {scope: :post_id}
  
  private
  def create_notification
    Notification.create(
      user: self.post.user, # 通知を受け取るユーザー
      notifiable: self
    )
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :name, presence: true
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  belongs_to :user
  belongs_to :genre
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :image, presence: true  
  validates :name, presence: true
  validates :body, presence: true
  validates :price, presence: true
  
  def self.search_for(content, method)
    if method == 'perfect'
      Post.where(name: content)
    elsif method == 'forward'
      Post.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      Post.where('name LIKE ?', '%' + content)
    else
      Post.where('name LIKE ?', '%' + content + '%')
    end
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  has_many :notifications, as: :notifiable, dependent: :destroy
  
  after_create :create_notification
  
  private  
  def create_notification
    Notification.create(
      user: followed, # 通知を受け取るユーザー（フォローされたユーザー）
      notifiable: self
    )
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  # フォローしている関連付け
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  # フォローされている関連付け
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # フォローしているユーザーを取得
  has_many :followings, through: :relationships, source: :followed
  # フォロワーを所得
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # 指定したユーザーをフォローする
  def follow(user)
    relationships.create(followed_id: user.id)
  end

  # 指定したユーザーのフォローを解除する
  def unfollow(user)
    relationships.find_by(followed_id: user.id).destroy
  end

  # 指定したユーザーをフォローしているかどうかを判定
  def following?(user)
    followings.include?(user)
  end
  
  def user_status
    if is_deleted == true
      "退会"
    else
      "有効"
    end
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com', name: "guest") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.nickname = "Guest" # 修正: nicknameを設定
    end
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(nickname: content)
    elsif method == 'forward'
      User.where('nickname LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('nickname LIKE ?', '%' + content)
    else
      User.where('nickname LIKE ?', '%' + content + '%')
    end
  end

  validates :name, presence: true
  validates :nickname, presence: true # nicknameに対するバリデーションが原因
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_search_options
  
  def set_search_options
    @search_options = ['ユーザー', '投稿']
  end  
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end 
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user_or_admin!
  

  def search
    if params[:search_target] == 'ユーザー'
      @results = User.search_for(params[:keyword], params[:method])
    elsif params[:search_target] == '投稿'
      @results = Post.search_for(params[:keyword], params[:method])
    end

    if params[:method] == '部分一致'
      @results = @results.where('name LIKE ?', '%' + params[:keyword] + '%')
    end
  end
  
  private
  
  def authenticate_user_or_admin!
    unless user_signed_in? || admin_signed_in?
      redirect_to new_user_session_path, alert: "アクセスするにはログインが必要です。"
    end
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name), class:"btn btn-success" %><br />
<% end %>

app/views/layouts/_flash.html.erb
<div class="mt-2">
    <% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-danger">
      <%= flash[:alert] %>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer style="position: bottom: 0; width: 100%;">
  <div class="footer container-fluid">
    <p>CopyRight Minkatsu</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light fixed-top">
    <div class="container">
      <a class="navbar-brand" href="/"><span class="highlight">Minkatsu</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Minkatsuとは", about_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to "投稿一覧", posts_path, class: 'nav-link' %></li>
            <li class="nav-item">
              <%= link_to notifications_path, class: 'nav-link' do %>
                <i class="fa-regular fa-bell"></i>通知
              <% end %>  
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa-regular fa-circle-user"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to mypage_path, class: 'dropdown-item btn-sm' do %>
                  <i class="fa-solid fa-user"></i> mypage
                <% end %>
                <div class="dropdown-divider"></div>
                <%= link_to favorites_path, class: 'dropdown-item btn-sm' do %>
                  <i class="fa-solid fa-heart"></i> いいね一覧
                <% end %>
                <div class="dropdown-divider"></div>
                <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item btn-sm' do %>
                  <i class="fa-solid fa-right-from-bracket"></i> ログアウト
                <% end %>
              </div>
            </li>
          <% elsif admin_signed_in? %>
            <%= render "admin/searches/form" %>
            <li class="nav-item"><%= link_to "会員一覧", admin_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to "投稿一覧", admin_posts_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to "ジャンル一覧", admin_genres_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to "コメント一覧", admin_comments_path, class: 'nav-link' %></li>
            <li class="nav-item"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link' %></li>
          <% else %>
            <li class="nav-item"><%= link_to "Minkatsuとは", about_path, class: 'nav-link' %></li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fa-regular fa-circle-user"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to new_user_registration_path, class: 'dropdown-item btn-sm' do %>
                  <i class="fa-solid fa-clipboard-user"></i> 新規登録
                <% end %>
                <div class="dropdown-divider"></div>
                <%= link_to new_user_session_path, class: 'dropdown-item btn-sm' do %>
                  <i class="fa-solid fa-right-to-bracket"></i> ログイン
                <% end %>
              </div>  
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_success_message.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success mt-2">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <title>Minkatsu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/521db94061.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('M_icon.png') %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="mb-4"></div>
      <main class="mb-auto">
        <%= yield %>
      </main>
    <div class="mb-4"></div>  
    <%= render 'layouts/footer' %>
  </body>
</html>